export const clerkAppearance = {
  variables: {
    colorBackground: "#27272a",
    colorInputBackground: "#18181b",
    colorInputText: "#fafafa",
    colorText: "#fafafa",
    colorTextSecondary: "#d4d4d8",
    colorTextOnPrimaryBackground: "#09090b",
    colorPrimary: "#fafafa",
    colorDanger: "#f87171",
    colorSuccess: "#a1a1aa",
    colorNeutral: "#a1a1aa",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
    fontFamilyButtons: "var(--font-geist-sans), system-ui, sans-serif",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "bg-zinc-900/80 border border-white/10 shadow-none rounded-2xl backdrop-blur-sm",
    headerTitle: "font-serif text-white tracking-tight",
    headerSubtitle: "text-zinc-400",
    socialButtonsBlockButton:
      "border border-white/10 bg-zinc-950 text-white hover:bg-zinc-800",
    socialButtonsBlockButtonText: "text-white font-medium",
    dividerLine: "bg-white/10",
    dividerText: "text-zinc-500",
    formFieldLabel: "text-zinc-300",
    formFieldInput:
      "border-white/10 bg-zinc-950 text-white placeholder:text-zinc-600 focus:border-white/20",
    formButtonPrimary:
      "rounded-full bg-white text-zinc-950 hover:bg-zinc-200 shadow-none",
    footerActionLink: "text-zinc-300 hover:text-white",
    identityPreviewText: "text-white",
    identityPreviewEditButton: "text-zinc-400 hover:text-white",
    formFieldInputShowPasswordButton: "text-zinc-400",
    alertText: "text-zinc-300",
    otpCodeFieldInput: "border-white/10 bg-zinc-950 text-white",
    navbarButton: "text-zinc-400",
    profileSectionTitle: "text-white",
    profileSectionContent: "text-zinc-300",
    accordionTriggerButton: "text-zinc-300",
    badge: "border-white/10 bg-zinc-800 text-zinc-200",
    userButtonPopoverCard:
      "!bg-zinc-800 border border-white/15 shadow-[0_20px_50px_-12px_rgba(0,0,0,0.65)] rounded-xl",
    userButtonPopoverMain: "text-zinc-100",
    userButtonPopoverActionButton:
      "text-zinc-200 hover:bg-zinc-700/80 rounded-lg transition-colors",
    userButtonPopoverActionButtonText: "text-zinc-100",
    userButtonPopoverActionButtonIcon: "text-zinc-400",
    userButtonPopoverFooter: "border-t border-white/10 bg-zinc-800/90",
    userPreviewMainIdentifier: "text-white font-medium",
    userPreviewSecondaryIdentifier: "text-zinc-400",
    menuList: "bg-zinc-800 border border-white/15 shadow-[0_20px_50px_-12px_rgba(0,0,0,0.65)]",
    menuItem: "text-zinc-200 hover:bg-zinc-700/80",
    menuButton: "text-zinc-200",
  },
  layout: {
    socialButtonsPlacement: "top",
    showOptionalFields: true,
  },
};
